---
test-name: "data-test"
base-url: "http://localhost:8080"
block-range:
  enabled: true
  start: 22631960
  end: 22631965
performance:
  concurrent-requests: 1
  total-requests: 100
  timeout-seconds: 30
  warm-up-requests: 0
  metrics:
    - "response_time"
    - "throughput"
    - "success_rate"
    - "error_rate"
endpoints:
  - path: "/network/list"
    method: "POST"
    payload:
      metadata: {}
  - path: "/network/options"
    method: "POST"
    payload:
      network_identifier:
        blockchain: "Ethereum"
        network: "Mainnet"
      metadata: {}
  - path: "/network/status"
    method: "POST"
    payload:
      network_identifier:
        blockchain: "Ethereum"
        network: "Mainnet"
      metadata: {}
  - path: "/block"
    method: "POST"
    uses-block-index: true
    payload:
      network_identifier:
        blockchain: "Ethereum"
        network: "Mainnet"
      block_identifier:
        index: 22631963
  - path: "/account/balance"
    method: "POST"
    uses-block-index: true
    payload:
      network_identifier:
        blockchain: "Ethereum"
        network: "Mainnet"
      account_identifier:
        address: "0xde0B295669a9FD93d5F28D9Ec85E40f4cb697BAe" # Ethereum Foundation Address
        metadata: {}
      block_identifier:
        index: 22631963
      currencies:
        - symbol: "ETH"
          decimals: 18
          metadata: {}